CREATE DATABASE IF NOT EXISTS peti_profered CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE peti_profered;

CREATE TABLE IF NOT EXISTS peti_secciones (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    seccion VARCHAR(120) NOT NULL UNIQUE,
    data_json JSON NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
